name: flutter_demo
description: Flutter基础使用案例

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/timg.jpg
    - images/1405166051589_middle.jpg
    - images/1405166057580_middle.jpg
    - images/1405166061660_middle.jpg
    - images/1405166072230_middle.jpg
    - images/tools.png
    - images/20180309142057.png
    - assets/config.json